import express, { Request, Response } from "express";
import dotenv from "dotenv";
import { RegisterRoutes } from "./routes/routes"; // generated by tsoa
import { setupSwagger } from "./swagger/setupSwagger"; // ✅ دقت به مسیر و {}
dotenv.config();

const app = express();
app.use(express.json());
setupSwagger(app);
app.get("/", (req: Request, res: Response) => {
  res.send("Server is running!");
});
RegisterRoutes(app);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
